import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Work_Sans,
  Jersey_10, Space_Grotesk, Space_Mono
} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/home/layout/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400"
})

const SpaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: "400"
})


const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const Jeysey10 = Jersey_10({
  variable: "--font-jersey-10",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${SpaceGrotesk.variable} ${spaceMono.variable} ${workSans.variable} ${inter.variable} ${Jeysey10.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
