use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u32)]
pub enum Error {
    Unauthorized = 2,
    SessionNotFound = 4,
    InvalidAmount = 5,
    DisputeNotFound = 8,
    TimelockNotExpired = 10,
    ProtocolPaused = 12,
    ReputationTooLow = 13,
    SessionExpired = 15,
    InvalidCid = 16,
    InvalidSplitBps = 17,
    DisputeWindowActive = 18,
    InvalidFeeConfig = 19,
    InsufficientTreasuryBalance = 20,
    AmountBelowMinimum = 21,
    ExpertNotRegistered = 22,
    ExpertUnavailable = 23,
    InvalidReferrer = 24,
    ReentrantCall = 25,
    AlreadyInitialized = 27,
    InvalidRating = 28,
    OracleNotTrusted = 30,
    InvalidSessionState = 33,
    InsufficientBalance = 34,
    StakeNotFound = 35,
    NoRewardsToClaim = 36,
    ContractUnset = 42,
    DisputeResolved = 45,
    BadgeAlreadyMinted = 46,
    HoursThresholdNotMet = 47,
    SessionFrozen = 48,
    SwapFailed = 49,
    ExpertOnCooldown = 50,
    SpendingLimitExceeded = 51,
    InvalidVoucher = 56,
    DisputeCoolingOff = 58,
    DisputeEscalated = 59,
    HandoffProposalNotFound = 60,
    SlippageExceeded = 64,
    CircuitBreakerActive = 68,
    SessionNotExpired = 69,
    JuryNotSelected = 70,
    JuryAlreadyVoted = 71,
    JuryVotingClosed = 72,
    InsufficientCandidates = 73,
    AppealBondRequired = 74,
    AppealAlreadyFiled = 75,
    AppealNotFound = 76,
    SurgeNotAccepted = 82,
}
